### PR TITLE
RAG - SharePoint template: Edit pass on metadata, parameter display names, and descriptions

### PR DESCRIPTION
**Pull request by ecfan**

### CODE REVIEW

**Comment by ecfan** [comment]
#assign:Elaina-Lee

**Comment by ecfan** [comment]
#assign:divyaswarnkar

**Comment by ecfan** [comment]
@divyaswarnkar & @Elaina-Lee: Please review the updates I made? Thanks!

**Comment by ecfan** [comment]
#assign @divyaswarnkar

**Review by Elaina-Lee — APPROVED** [review]

**Pull request merged**
